// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.6.1
// source: fdoonboarding.proto

package grpc_demo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	NodeArtifactServiceNB_FdoOnboardingTo2Req_FullMethodName = "/NodeArtifactServiceNB/FdoOnboardingTo2Req"
)

// NodeArtifactServiceNBClient is the client API for NodeArtifactServiceNB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeArtifactServiceNBClient interface {
	FdoOnboardingTo2Req(ctx context.Context, in *FdoOnboardingReq, opts ...grpc.CallOption) (*FdoOnboardingResponse, error)
}

type nodeArtifactServiceNBClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeArtifactServiceNBClient(cc grpc.ClientConnInterface) NodeArtifactServiceNBClient {
	return &nodeArtifactServiceNBClient{cc}
}

func (c *nodeArtifactServiceNBClient) FdoOnboardingTo2Req(ctx context.Context, in *FdoOnboardingReq, opts ...grpc.CallOption) (*FdoOnboardingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FdoOnboardingResponse)
	err := c.cc.Invoke(ctx, NodeArtifactServiceNB_FdoOnboardingTo2Req_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeArtifactServiceNBServer is the server API for NodeArtifactServiceNB service.
// All implementations must embed UnimplementedNodeArtifactServiceNBServer
// for forward compatibility
type NodeArtifactServiceNBServer interface {
	FdoOnboardingTo2Req(context.Context, *FdoOnboardingReq) (*FdoOnboardingResponse, error)
	mustEmbedUnimplementedNodeArtifactServiceNBServer()
}

// UnimplementedNodeArtifactServiceNBServer must be embedded to have forward compatible implementations.
type UnimplementedNodeArtifactServiceNBServer struct {
}

func (UnimplementedNodeArtifactServiceNBServer) FdoOnboardingTo2Req(context.Context, *FdoOnboardingReq) (*FdoOnboardingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FdoOnboardingTo2Req not implemented")
}
func (UnimplementedNodeArtifactServiceNBServer) mustEmbedUnimplementedNodeArtifactServiceNBServer() {}

// UnsafeNodeArtifactServiceNBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeArtifactServiceNBServer will
// result in compilation errors.
type UnsafeNodeArtifactServiceNBServer interface {
	mustEmbedUnimplementedNodeArtifactServiceNBServer()
}

func RegisterNodeArtifactServiceNBServer(s grpc.ServiceRegistrar, srv NodeArtifactServiceNBServer) {
	s.RegisterService(&NodeArtifactServiceNB_ServiceDesc, srv)
}

func _NodeArtifactServiceNB_FdoOnboardingTo2Req_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FdoOnboardingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeArtifactServiceNBServer).FdoOnboardingTo2Req(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeArtifactServiceNB_FdoOnboardingTo2Req_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeArtifactServiceNBServer).FdoOnboardingTo2Req(ctx, req.(*FdoOnboardingReq))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeArtifactServiceNB_ServiceDesc is the grpc.ServiceDesc for NodeArtifactServiceNB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeArtifactServiceNB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "NodeArtifactServiceNB",
	HandlerType: (*NodeArtifactServiceNBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FdoOnboardingTo2Req",
			Handler:    _NodeArtifactServiceNB_FdoOnboardingTo2Req_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fdoonboarding.proto",
}
